# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-25 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import forsol.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=forsol.models.subir_media)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[(b'Principal', b'Principal'), (b'Noticias', b'Noticias'), (b'Tutoriales', b'Tutos'), (b'Eventos', b'Eventos')], max_length=30)),
                ('texto', models.TextField()),
                ('imagen', models.FileField(blank=True, null=True, upload_to=forsol.models.subir_file)),
                ('fecha_post', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
