# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[(b'Principal', b'Principal'), (b'Noticias', b'Noticias'), (b'Tutoriales', b'Tutos'), (b'Eventos', b'Eventos'), (b'Proyectos', b'Proyectos')], max_length=30),
        ),
    ]
