# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsol', '0002_auto_20190926_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
    ]
